package com.framework.utils.xml;

/**
 * Created with IntelliJ IDEA ( LivePerson : www.liveperson.com )
 *
 * Package: com.framework.utils.xml
 *
 * Name   : XmlParseException 
 *
 * User   : solmarkn / Dani Vainstein
 *
 * Date   : 2015-02-15 
 *
 * Time   : 16:30
 *
 */

public class XmlParseException extends RuntimeException
{
	/** generated by IntelliJ IDEA */
	private static final long serialVersionUID = 8820883219804905698L;

	public XmlParseException( final String message )
	{
		super( message );
	}

	public XmlParseException( final String message, final Throwable cause )
	{
		super( message, cause );
	}

	public XmlParseException( final Throwable cause )
	{
		super( cause );
	}
}
